# Generated by Django 4.2.10 on 2026-03-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='sample_input',
            field=models.TextField(blank=True, default='', help_text='Shown to user, used for Run'),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_output',
            field=models.TextField(blank=True, default='', help_text='Shown to user, used for Run'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_cases',
            field=models.JSONField(default=list, help_text='Hidden test cases — backend only, never sent to frontend'),
        ),
    ]
