# Generated by Django 5.0.6 on 2026-03-02 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SabotageMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(choices=[('SCREEN_WIPE', 'Screen Wipe'), ('FOG_OF_WAR', 'Fog of War'), ('CODE_SCRAMBLE', 'Code Scramble'), ('TIME_STEAL', 'Time Steal')], max_length=32)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabotage_moves', to=settings.AUTH_USER_MODEL)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabotage_moves', to='battles.battle')),
            ],
        ),
    ]
