# Generated by Django 4.2.10 on 2026-03-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabotage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sabotagemove',
            name='move_type',
            field=models.CharField(choices=[('GARBAGE_COLLECTION', 'Garbage Collection')], max_length=32),
        ),
    ]
