# Generated by Django 4.2.10 on 2026-03-14 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battles', '0002_battlerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='user',
            new_name='player',
        ),
        migrations.AddField(
            model_name='submission',
            name='complexity_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='execution_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='passed_cases',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='total_cases',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('battle', 'player', 'problem')},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='complexity_score',
        ),
    ]
