# Generated by Django 5.0.6 on 2026-03-23 05:32

from datetime import timedelta

from django.db import migrations, models


def backfill_ends_at(apps, schema_editor):
    Battle = apps.get_model("battles", "Battle")
    for b in Battle.objects.filter(ends_at__isnull=True).iterator():
        b.ends_at = b.created_at + timedelta(minutes=30)
        b.save(update_fields=["ends_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0006_battle_reward_spectator_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='When the match auto-ends (typically 30 minutes after going active).', null=True),
        ),
        migrations.RunPython(backfill_ends_at, migrations.RunPython.noop),
    ]
