# Generated by Django 5.0.6 on 2026-07-26 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0008_battle_ended_reason_resigned_by'),
        ('problems', '0005_expand_arena_problem_pool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['status', '-created_at'], name='battle_status_created'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['status', 'ends_at'], name='battle_status_ends_at'),
        ),
        migrations.AddIndex(
            model_name='battlerequest',
            index=models.Index(fields=['to_user', 'status'], name='battlereq_to_user_status'),
        ),
        migrations.AddIndex(
            model_name='battlerequest',
            index=models.Index(fields=['status', 'expires_at'], name='battlereq_status_expires'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['battle', 'problem', 'status'], name='submission_battle_prob_st'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['battle', 'player'], name='submission_battle_player'),
        ),
        migrations.AddConstraint(
            model_name='battle',
            constraint=models.CheckConstraint(check=models.Q(('player1', models.F('player2')), _negated=True), name='battle_players_must_differ'),
        ),
    ]
