# Generated by Django 5.0.6 on 2026-08-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0009_harden_battle_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='player1_time_ms',
        ),
        migrations.RemoveField(
            model_name='round',
            name='player2_time_ms',
        ),
    ]
