# Generated by Django 5.0.6 on 2026-08-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0010_remove_round_player1_time_ms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='round',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='complexity_class',
        ),
    ]
